### ISSUE TITLE
AnalyzeDocument unsupported document type error when uploading PDF doc to S3

### ISSUE THREAD

**Issue by Bazza1297** [aws-samples/amazon-textract-comprehend-OCRimage-search-and-analyze#4]
Cloudwatch extract:

Object downloaded

An error occurred (UnsupportedDocumentException) when calling the AnalyzeDocument operation: Request has unsupported document format

An error occurred (UnsupportedDocumentException) when calling the AnalyzeDocument operation: Request has unsupported document format: UnsupportedDocumentException
Traceback (most recent call last):
  File "/var/task/comprehend.py", line 161, in handler
    raise e
  File "/var/task/comprehend.py", line 123, in handler
    response = textract.analyze_document(Document={'Bytes': imageBytes},FeatureTypes=["TABLES", "FORMS"])
  File "/var/runtime/botocore/client.py", line 316, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/var/runtime/botocore/client.py", line 635, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.UnsupportedDocumentException: An error occurred (UnsupportedDocumentException) when calling the AnalyzeDocument operation: Request has unsupported document format

END RequestId: d3fd1d82-dbf8-4a68-8617-86155f3c68c0

**Comment by Bazza1297** [comment]
False flag. My input was multipage PDFs which this stack is not designed for.
